export const ADMIN_ROUTE = '/admin' 
export const LOGIN_ROUTE = '/login'
export const ABOUT_ROUTE = '/about'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const USERPROFILE_ROUTE = '/user'
export const HOUSING_ROUTE = '/housing'
export const CREATEHOUSING_ROUTE = '/create'